import './globals.css';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import React from 'react';

const inter = Roboto({ subsets: ['latin'], weight: ['100', '300', '400', '500', '700', '900'] });

export const metadata: Metadata = {
  title: 'PatternPallete',
  description: 'Generated by create next app',
  icons: 'logoP.svg'
};

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
