import './globals.css';
import { Analytics } from '@vercel/analytics/react';
import type { Metadata } from 'next';
import { Kanit } from 'next/font/google';
import React from 'react';

const inter = Kanit({ subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '600', '700'] });

export const metadata: Metadata = {
  title: 'Patterns for Css and Tailwind | PatternPallete',
  description: 'Generated by create next app',
  icons: 'logo.svg'
};

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}  min-h-[100vh]`}>
        {children}
        <Analytics/>
      </body>
    </html>
  );
}
